oxts_ins:
  ros__parameters:
#===============================================================================
    # INS configuration (set up to match the unit)
    ## Unit IP address
    unit_ip: 192.168.25.44
    ## Unit Port (3000 unless intentionally configured otherwise on the INS)
    unit_port: 3000

#===============================================================================
    # Configure ROS messages to be published by the node.
    ## Frames
    frame_id            : "oxts_link"
    ## Configure output rates of individual topics
    ## Rates must be factors of the ncom_rate, configured above.
    ## Rates are in Hz. 0 Hz => Message will not be published
    ### Configure sample rate of NCom (do not exceed output rate of ncom)
    ncom_rate               : 100
    ### Publish string message
    pub_string_rate         : 0
    ### Publish NavSatFix message
    pub_nav_sat_fix_rate    : 5
    ### Publish Velocity message
    pub_velocity_rate       : 10
    ### Publish Odometry message
    pub_odometry_rate       : 10
    ### Defaults to "map", can be set to "odom" when emulating navsat_transform_node
    pub_odometry_frame_id   : "map"
    ### Publish TimeReference message
    pub_time_reference_rate : 1
    ### Publish PoseWithCovarianceStamped message
    pub_ecef_pos_rate       : 10
    ### Publish OxTS NavSatRef message
    pub_nav_sat_ref_rate    : 10
    ### Publish Imu message
    pub_imu_flag            : true
    ### Broadcast Tf messages for rviz visualisation
    pub_tf_flag             : true
    ### Source of the local reference frame
    #### 0 - NCom LRF
    #### 1 - Set automatically from first NCom packet
    #### 2 - Set automatically from first position of NCom packet aligned to ENU
    lrf_source              : 2

#===============================================================================
    ## Timing - how to timestamp messages published by the ROS driver

    # 0 => Timestamped by the ROS node time (future default)
    # 1 => Timestamped from NCom
    timestamp_mode : 1