ncom_publisher:
  ros__parameters:
#===============================================================================
    # INS configuration (set up to match the unit)
    ## Configure sample rate of NCom (do not exceed output rate of ncom)
    ncom_rate: 100.0
    ## Unit IP address
    unit_ip: "192.168.25.216"
    ## Unit Port
    unit_port: 3000
#===============================================================================
    # Configure ROS messages to be published by the node.
    ## Frames
    frame_id            : "oxts_link"
    ## Configure output rates of individual topics
    ## Rates must be factors of the ncom_rate, configured above.
    ## Rates are in Hz. 0 Hz => Message will not be published
    ### Publish ROS string message
    pub_string_rate           : 1.0
    ### Publish ROS Odometry message
    pub_odometry_rate         : 1.0
    ### Publish ROS NavSatFix message
    pub_nav_sat_fix_rate      : 5.0
    ### Publish ROS Imu message
    pub_imu_rate              : 100.0
    ### Publish ROS Velocity message
    pub_velocity_rate         : 5.0
    ### Publish ROS TimeReference message
    pub_time_reference_rate   : 1.0
    ### Publish ROS Tf2 message
    pub_tf2_rate              : 10.0

#===============================================================================
    ## Timing - how to timestamp messages published by the ROS driver
    # NOT YET IMPLEMENTED

    # 0 => Timestamped by the ROS node time (future default)
    # 1 => Timestamped from NCom
    timestamp_mode : 1