oxts_driver:
  ros__parameters:
#===============================================================================
    # INS configuration (set up to match the unit)
    ## Unit IP address
    unit_ip: 195.0.0.96
    ## Unit Port (3000 unless intentionally configured otherwise on the INS)
    unit_port: 3000

#===============================================================================
    # Configure ROS messages to be published by the node.
    ## Frames
    frame_id            : "oxts_link"
    ## Configure output rates of individual topics
    ## Rates must be factors of the ncom_rate, configured above.
    ## Rates are in Hz. 0 Hz => Message will not be published
    ### Configure sample rate of NCom (do not exceed output rate of ncom)
    ncom_rate               : 100.0
    ### Publish ROS string message
    pub_string_rate         : 1.0
    ### Publish ROS NavSatFix message
    pub_nav_sat_fix_rate    : 5.0
    ### Publish ROS Imu message
    pub_imu_rate            : 100.0
    ### Publish ROS Velocity message
    pub_velocity_rate       : 10.0
    ### Publish ROS TimeReference message
    pub_time_reference_rate : 1.0
    ### Publish ROS PoseWithCovarianceStamped message
    pub_ecef_pos_rate       : 10.0
    ### Broadcast Tf messages for rviz visualisation
    pub_tf_flag             : 1

#===============================================================================
    ## Timing - how to timestamp messages published by the ROS driver

    # 0 => Timestamped by the ROS node time (future default)
    # 1 => Timestamped from NCom
    timestamp_mode : 1